language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.4
 - 5.5
# - 5.6
# - 7.0

matrix:
 fast_finish: true
 allow_failures:
  - php: 7.0

env:
 matrix:
  - DB=pgsql MOODLE_BRANCH=MOODLE_27_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_28_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
  - sed -i.bak "s/\/\/ Get the module context./\\\\local_recyclebin\\\\observer::pre_cm_delete(\$cm);/g" /home/travis/build/moodle/course/lib.php
  - sed -i.bak "s/\/\/ Make the course completely empty./\\\\local_recyclebin\\\\observer::pre_course_delete(\$course);/g" /home/travis/build/moodle/lib/moodlelib.php

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
#  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
#  - moodle-plugin-ci csslint
#  - moodle-plugin-ci shifter
#  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
#  - moodle-plugin-ci behat
